# Generated by Django 5.1.1 on 2024-09-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='discussion_count',
            field=models.IntegerField(default=0),
        ),
    ]
