# Generated by Django 5.1.1 on 2024-09-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_film_discussion_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
