# Generated by Django 5.1.1 on 2024-09-14 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_film_review_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('discussion_id', models.AutoField(primary_key=True, serialize=False)),
                ('discussion_header', models.CharField(max_length=1000)),
                ('discussion_content', models.TextField()),
                ('discussion_date', models.DateTimeField(auto_now_add=True)),
                ('discussion_likes', models.IntegerField(default=0)),
                ('discussion_replies', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.usersapp')),
            ],
        ),
    ]
