# Generated by Django 5.1.1 on 2024-09-14 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_discussion_discussion_film'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionComments',
            fields=[
                ('discussion_comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('discussion_comment_content', models.TextField()),
                ('discussion_comment_date', models.DateTimeField(auto_now_add=True)),
                ('discussion_comment_likes', models.IntegerField(default=0)),
                ('discussion', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.discussion')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.discussioncomments')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.usersapp')),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionLikes',
            fields=[
                ('discussion_like_id', models.AutoField(primary_key=True, serialize=False)),
                ('discussion', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.discussion')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.usersapp')),
            ],
        ),
    ]
